name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy API
        run: |
          chmod +x deploy-api.sh
          ./deploy-api.sh

  deploy-client:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Client
        run: |
          chmod +x deploy-client.sh
          ./deploy-client.sh
