name: CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  api:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ./api
        run: npm install

      - name: Give execute permissions to Prettier
        working-directory: ./api
        run: chmod +x node_modules/.bin/prettier

      - name: Check and fix code format
        working-directory: ./api
        run: npm run format:fix

      - name: Lint code
        working-directory: ./api
        run: npm run lint

      - name: Build project
        working-directory: ./api
        run: npm run build

      - name: Run tests
        working-directory: ./api
        run: npm test

  client:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Give execute permissions to Prettier
        working-directory: ./client
        run: chmod +x node_modules/.bin/prettier

      - name: Check and fix code format
        working-directory: ./client
        run: npm run format:fix

      - name: Lint code
        working-directory: ./client
        run: npm run lint

      - name: Build project
        working-directory: ./client
        run: npm run build

      - name: Run tests
        working-directory: ./client
        run: npm test
